In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

filename = ("/content/drive/MyDrive/Control6.csv")
Dataframe = pd.read_csv(filename)
Groups = Dataframe['Group'].unique()

for i in Groups:
  print("CURRENT GROUPNUMBER IS: " + str(i))
  df = Dataframe.loc[Dataframe['Group'] == i]
  Participants = df['Subject'].unique()

  Player_moves = {}

  for player_number in Participants:
    key = 'Player_{}'.format(player_number)
    array = df.loc[df['Subject'] == player_number]['Action_real'].copy()
    Player_moves[key] = array
  
  keys = list(Player_moves.keys())

  Player1 = Player_moves[keys[0]].values
  Player2 = Player_moves[keys[1]].values

  #0 is 00, 1 is 01 (your own choice was 1), 10, 11
  #And in _0 means the action taken was 0
  Situations1_0 = np.zeros(4)
  Situations1_1 = np.zeros(4)

  Situations2_0 = np.zeros(4)
  Situations2_1 = np.zeros(4)

  #CAREFUL THIS CURRENTLY NEGATES FIRST PERIOD
  for i in range(1,100):
    action_1 = Player1[i]
    prev_action_1 = Player1[i-1]
    

    action_2 = Player2[i]
    prev_action_2 = Player2[i-1]

    if (action_1 == 0):
      Situations1_0[prev_action_1 + (2*prev_action_2)] +=1
    else:
      Situations1_1[prev_action_1 + (2*prev_action_2)] +=1

    if (action_2 == 0):
      Situations2_0[prev_action_2 + (2*prev_action_1)] +=1
    else:
      Situations2_1[prev_action_2 + (2*prev_action_1)] +=1

  
  print(Situations1_0)
  print(Situations1_1)
  print(Situations2_0)
  print(Situations2_1)

  print("PLAYER1 STATS given OWN ACTION")
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations1_0[0] + Situations1_0[2]))
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations1_0[1] + Situations1_0[3]))

  print("AMOUNT OF TIMES 1 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations1_1[0] + Situations1_1[2]))
  print("AMOUNT OF TIMES 1 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations1_1[1] + Situations1_1[3]))

  print("PLAYER1 STATS given OPP ACTION")
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations1_0[0] + Situations1_0[1]))
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations1_0[2] + Situations1_0[3]))

  print("AMOUNT OF TIMES 1 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations1_1[0] + Situations1_1[1]))
  print("AMOUNT OF TIMES 1 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations1_1[2] + Situations1_1[3]))

  print("PLAYER2 STATS given OWN ACTION")
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations2_0[0] + Situations2_0[2]))
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations2_0[1] + Situations2_0[3]))

  print("AMOUNT OF TIMES 1 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations2_1[0] + Situations2_1[2]))
  print("AMOUNT OF TIMES 1 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations2_1[1] + Situations2_1[3]))

  print("PLAYER2 STATS given OPP ACTION")
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations2_0[0] + Situations2_0[1]))
  print("AMOUNT OF TIMES 0 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations2_0[2] + Situations2_0[3]))

  print("AMOUNT OF TIMES 1 CHOSEN WHEN 0 PREVIOUSLY: " + str(Situations2_1[0] + Situations2_1[1]))
  print("AMOUNT OF TIMES 1 CHOSEN WHEN 1 PREVIOUSLY: " + str(Situations2_1[2] + Situations2_1[3]))

  print("----------------------------------------------------------------------------------------")


  


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CURRENT GROUPNUMBER IS: 1
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 2
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 3
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 4
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 5
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 6
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 7
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 8
----------------------------------------

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

filename = ("/content/drive/MyDrive/Control6.csv")
Dataframe = pd.read_csv(filename)
Groups = Dataframe['Group'].unique()

total_payout = []
for i in range(0,101):
  total_payout.append(0)
problem_groups = [3,4,6,7,8,9,15]
for i in problem_groups:
  print("CURRENT GROUPNUMBER IS: " + str(i))
  df = Dataframe.loc[Dataframe['Group'] == i]
  Participants = df['Subject'].unique()

  Player_moves = {}

  for player_number in Participants:
    key = 'Player_{}'.format(player_number)
    array = df.loc[df['Subject'] == player_number]['Action_real'].copy()
    Player_moves[key] = array
  
  keys = list(Player_moves.keys())

  Player1 = Player_moves[keys[0]].values
  Player2 = Player_moves[keys[1]].values

  #0 is 00, 1 is 01 (your own choice was 1), 10, 11
  #And in _0 means the action taken was 0
  '''Situations1_0 = np.zeros(4)
  Situations1_1 = np.zeros(4)

  Situations2_0 = np.zeros(4)
  Situations2_1 = np.zeros(4)'''

  share = 0
  steal = 0
  stolen = 0
  nothing = 0

  payout_row = []
  #CAREFUL THIS CURRENTLY NEGATES FIRST PERIOD

  for i in range(1,100):
    Action1 = Player1[i]
    Action2 = Player2[i]
    if (Action1 == 0):
      if (Action2 == 0):
        nothing += 1
        payout_row.append(0)
        total_payout[i] += 0
      else:
        steal += 1
        payout_row.append(10)
        total_payout[i] += 10
    else:
      if (Action2 == 0):
        stolen += 1
        payout_row.append(0)
        total_payout[i] += 0
      else:
        share += 1    
        payout_row.append(7)
        total_payout[i] += 7

  total_earned = 7*share + 10*steal  
  enemy_earned = 7*share + 10*stolen

  print("SHARE: " + str(share))
  print("NOTHING: " + str(nothing))
  print("STEAL: " + str(steal))
  print("STOLEN: " + str(stolen))
  print("TOTAL EARNED: " + str(total_earned))
  print("ENEMY EARNED: " +str(enemy_earned))
  print(payout_row)


  print("----------------------------------------------------------------------------------------")
print(total_payout)
#Dataframe = pd.read_csv("/content/drive/MyDrive/Simulations/testing_combined.csv")
#del Dataframe['Right']
#del Dataframe['Unsure']



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CURRENT GROUPNUMBER IS: 3
SHARE: 19
NOTHING: 42
STEAL: 4
STOLEN: 34
TOTAL EARNED: 173
ENEMY EARNED: 473
[0, 0, 10, 10, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
----------------------------------------------------------------------------------------
CURRENT GROUPNUMBER IS: 4
SHARE: 64
NOTHING: 11
STEAL: 13
STOLEN: 11
TOTAL EARNED: 578
ENEMY EARNED: 558
[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 10, 0, 7, 7, 10, 0, 7, 10, 0, 10, 0, 7, 7, 10, 0, 10, 0, 0, 7, 7, 10, 0, 7, 10, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 10, 0, 7, 7, 7, 7, 7, 7, 10, 0, 10, 0, 7, 7, 7, 10, 0, 7, 7, 7, 7, 

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

filename = ("/content/drive/MyDrive/Control6.csv")
Dataframe = pd.read_csv(filename)
Groups = Dataframe['Group'].unique()

total_payout = []
for i in range(0,101):
  total_payout.append(0)

#for i in problem_groups:
for i in range(1,11):
  print("CURRENT GROUPNUMBER IS: " + str(i))
  df = Dataframe.loc[Dataframe['Group'] == i]
  Participants = df['Subject'].unique()

  Player_moves = {}

  for player_number in Participants:
    key = 'Player_{}'.format(player_number)
    array = df.loc[df['Subject'] == player_number]['Action_real'].copy()
    Player_moves[key] = array
  
  keys = list(Player_moves.keys())

  Player1 = Player_moves[keys[0]].values
  Player2 = Player_moves[keys[1]].values

  #0 is 00, 1 is 01 (your own choice was 1), 10, 11
  #And in _0 means the action taken was 0
  '''Situations1_0 = np.zeros(4)
  Situations1_1 = np.zeros(4)

  Situations2_0 = np.zeros(4)
  Situations2_1 = np.zeros(4)'''

  share = 0
  steal = 0
  stolen = 0
  nothing = 0

  payout_row = []
  #CAREFUL THIS CURRENTLY NEGATES FIRST PERIOD

  for i in range(1,100):
    Action1 = Player1[i]
    Action2 = Player2[i]
    if (Action1 == 0):
      if (Action2 == 0):
        nothing += 1
        payout_row.append(0)
        total_payout[i] += 0
      else:
        steal += 1
        payout_row.append(10)
        total_payout[i] += 10
    else:
      if (Action2 == 0):
        stolen += 1
        payout_row.append(0)
        total_payout[i] += 0
      else:
        share += 1    
        payout_row.append(7)
        total_payout[i] += 7

  total_earned = 7*share + 10*steal  
  enemy_earned = 7*share + 10*stolen

  print("SHARE: " + str(share))
  print("NOTHING: " + str(nothing))
  print("STEAL: " + str(steal))
  print("STOLEN: " + str(stolen))
  print("TOTAL EARNED: " + str(total_earned))
  print("ENEMY EARNED: " +str(enemy_earned))
  print(payout_row)


  print("----------------------------------------------------------------------------------------")
print(total_payout)




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


FileNotFoundError: ignored

In [ ]:
Dataframe = pd.read_csv("/content/drive/MyDrive/Simulations/testing_combined.csv")
#del Dataframe['Wrong']
#del Dataframe['Right']
print(Dataframe.loc[Dataframe['Comb'] == 9227694])

          Unnamed: 0     Comb  Right  Unsure  Wrong
808099        808099  9227694     31       8     31
11136462    11136462  9227694     42       7     21
27913653    27913653  9227694     54       4     12
44690844    44690844  9227694     40       9     21
61468035    61468035  9227694     60       2      8
78245226    78245226  9227694     55       4     11
95022417    95022417  9227694     55       5     10


In [ ]:
Dataframe = Dataframe.groupby(['Comb'])

In [ ]:
Dataframe = Dataframe.mean()
Dataframe = Dataframe.sort_values('Unsure')
name_to_use = 'Unsure' + ".csv"
Dataframe.to_csv(name_to_use)

In [ ]:
from google.colab import files 
uploaded = files.upload()

In [ ]:
def walk_over_directories(rootdir, files_to_use):
  all_period_array = []
  index_errors = np.zeros(100)
  cur_lowest_errors = 100
  for dir in sorted(os.listdir(rootdir)):
    #print(str(os.listdir(rootdir)))
    cur_period = dir[8:]
    if np.int(cur_period) not in files_to_use:
      continue
    filename = "/Simulation6_" + str(groupnumber) + "_" + str(cur_period) + ".csv"
    Dataframe = pd.read_csv(rootdir + dir + filename )
    print("CURRENTLY USING " + str(rootdir + dir + filename))

    Period_errors = np.zeros(10)
    Periods = Dataframe['Period'].dropna().unique()

    periods_wrong = []
    Q_diff_CORRECT = []
    Q_diff_WRONG = []
    wrong = 0
    #for i in Periods:
    for i in range(31, 101):
      cur_periodic_part = np.int(np.ceil(i/10 - 1))
      iteration = Dataframe.loc[Dataframe['Period'] == i]
      occurence_count = iteration['Occurence count'].values
      if (iteration['Real action'].values == iteration['Predicted taken'].values):
        #("EQUAL")
        Q_diff_CORRECT.append(iteration['Q-value diff'])
      else:
        #("NOT EQUAL")
        #print(str(occurence_count) + " ON PERIOD: " + str(i))
        Period_errors[cur_periodic_part] +=1
        wrong += 1 
        Q_diff_WRONG.append(iteration['Q-value diff'])
        periods_wrong.append(i)
        i = np.int(i)
        index_errors[i-1] += 1

    print(Period_errors)
    #print("MEAN Q DIFF FOR CORRECT: "  + str(np.mean(Q_diff_CORRECT)))
    #print("MEAN Q DIFF FOR WRONG: "  + str(np.mean(Q_diff_WRONG)))
    print("TOTAL AMOUNT WRONG: " + str(wrong))
    print("PERIODS WRONG: " + str(periods_wrong))
    if (len(periods_wrong) < cur_lowest_errors):
      cur_lowest_errors = len(periods_wrong)
    all_period_array.append(periods_wrong)

  return all_period_array, index_errors

def total_errors_for_plot(rootdir, files_to_use, outputfile):
  for i in range(31, 101):
    all_period_array = []
    index_errors = np.zeros(100)
    cur_lowest_errors = 100

    period_errors_total = np.zeros(10)


    for dir in sorted(os.listdir(rootdir)):
      #print(str(os.listdir(rootdir)))
      cur_period = dir[8:]
      if np.int(cur_period) not in files_to_use:
        continue
      filename = "/Simulation6_" + str(groupnumber) + "_" + str(cur_period) + ".csv"
      Dataframe = pd.read_csv(rootdir + dir + filename )
      print("CURRENTLY USING " + str(rootdir + dir + filename))

      Period_errors = np.zeros(10)
      Periods = Dataframe['Period'].dropna().unique()

      periods_wrong = []
      Q_diff_CORRECT = []
      Q_diff_WRONG = []
      wrong = 0
      #for i in Periods:
      #for i in range(31, 101):
      cur_periodic_part = np.int(np.ceil(i/10 - 1))
      iteration = Dataframe.loc[Dataframe['Period'] == i]
      occurence_count = iteration['Occurence count'].values
      if (iteration['Real action'].values == iteration['Predicted taken'].values):
        #("EQUAL")
        Q_diff_CORRECT.append(iteration['Q-value diff'])
      else:
        #("NOT EQUAL")
        #print(str(occurence_count) + " ON PERIOD: " + str(i))
        Period_errors[cur_periodic_part] +=1
        wrong += 1 
        Q_diff_WRONG.append(iteration['Q-value diff'])
        periods_wrong.append(i)
        i = np.int(i)
        index_errors[i-1] += 1

      print(Period_errors)
      period_errors_total += Period_errors
      #print("MEAN Q DIFF FOR CORRECT: "  + str(np.mean(Q_diff_CORRECT)))
      #print("MEAN Q DIFF FOR WRONG: "  + str(np.mean(Q_diff_WRONG)))
      #print("TOTAL AMOUNT WRONG: " + str(wrong))
      #print("PERIODS WRONG: " + str(periods_wrong))
      if (len(periods_wrong) < cur_lowest_errors):
        cur_lowest_errors = len(periods_wrong)
      all_period_array.append(periods_wrong)
    write_to_csv(outputfile, [period_errors_total], 'Period errors' )
  return all_period_array, index_errors

def combine_classifiers_results(array_with_period_errors, data_to_write):
  full_period_array = array_with_period_errors
  max_decimal = len(full_period_array)
  #Iterate all possible combinations NOTE: this is (2^x)-1, but because range incoorporates this -1 you can just do 2**x
  current_highest_right = 0
  current_lowest_wrong = 100
  highest_lowest_diff = 0
  for i in tqdm(range(2**max_decimal)):
  #for i in [2053]:

    temp = "{0:0" + str(max_decimal) + "b}"
    x = temp.format(i)

    amount_classifiers_used = 0
    error_places = np.zeros(100)
    for k in range(max_decimal):
      if(np.int(x[k]) == 1):
        amount_classifiers_used += 1
        for l in full_period_array[k]:
          error_places[l-1] += 1
    #print(error_places)

    wrong_classified = 0
    right_classified = 0
    unsure_classified = 0

    if (amount_classifiers_used < 2):
      continue
    #IF amount of classifiers is even
    if (amount_classifiers_used%2) == 0:
      threshold = (amount_classifiers_used)/2
      for z in range(30,100):
        cur_error_number = np.int(error_places[z])
        if(cur_error_number < threshold):
          right_classified +=1
        elif(cur_error_number == threshold):
          unsure_classified +=1
        else:
          wrong_classified +=1
    #IF amount is odd
    else:
      threshold_base = (amount_classifiers_used-1)/2
      for z in range(30,100):
        cur_error_number = np.int(error_places[z])
        if(cur_error_number < threshold_base):
          right_classified +=1
        elif(cur_error_number == threshold_base):
          unsure_classified +=1
        elif(cur_error_number == threshold_base+1):
          unsure_classified +=1
        else:
          wrong_classified +=1
    if(right_classified < wrong_classified):
      continue

    if(right_classified > current_highest_right):
      current_highest_right = right_classified
    if (right_classified - wrong_classified > highest_lowest_diff):
      highest_lowest_diff = right_classified - wrong_classified
    if(wrong_classified < current_lowest_wrong):
      current_lowest_wrong = wrong_classified
    data_to_write.append([i, right_classified, unsure_classified, wrong_classified])

    print("------------------------------------")
    print(x)
    print("RIGHT: " + str(right_classified) + "    UNSURE: " + str(unsure_classified) + "    WRONG: " + str(wrong_classified))

  print("HIGHEST RIGHT WAS: " + str(current_highest_right))
  print("LOWEST WRONG WAS: " + str(current_lowest_wrong))
  print("HIGHEST DIFF WAS: " + str(highest_lowest_diff))



def write_to_csv(outputfile, data, header):
  with open(outputfile, 'w', encoding = 'UTF8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(data)

def analyze_combined_stats(filename, sortby):
  Dataframe = pd.read_csv(filename)
  Dataframe = Dataframe.groupby(['Comb']).mean()
  Dataframe = Dataframe.sort_values(sortby)
  name_to_use = sortby + ".csv"
  Dataframe.to_csv(name_to_use)


In [ ]:
import os

rootdir = ("/content/drive/MyDrive/Simulations/Opposing/")
rootdir2 = ("/content/drive/MyDrive/Simulations/Baseline/")
rootdir3 = ("/content/drive/MyDrive/Simulations/LastOppo/")
rootdir4 = ("/content/drive/MyDrive/Simulations/PredOppo/")

walk_over_directories(rootdir, [5,10,15,20,25,30])
walk_over_directories(rootdir2, [5,10,15,20,25,30])
walk_over_directories(rootdir3, [5,10,15,20,25,30])
walk_over_directories(rootdir4, [5,10,15,20,25,30])


CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing10/Simulation6_8_10.csv
[0. 0. 0. 5. 4. 0. 0. 0. 0. 0.]
TOTAL AMOUNT WRONG: 9
PERIODS WRONG: [31, 32, 35, 36, 39, 42, 43, 45, 48]
CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing15/Simulation6_8_15.csv
[0. 0. 0. 4. 5. 0. 0. 0. 0. 0.]
TOTAL AMOUNT WRONG: 9
PERIODS WRONG: [32, 33, 34, 36, 42, 43, 45, 46, 47]
CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing20/Simulation6_8_20.csv
[0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
TOTAL AMOUNT WRONG: 8
PERIODS WRONG: [32, 33, 34, 35, 36, 42, 43, 46]
CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing25/Simulation6_8_25.csv
[0. 0. 0. 4. 6. 0. 0. 0. 0. 0.]
TOTAL AMOUNT WRONG: 10
PERIODS WRONG: [32, 33, 35, 37, 42, 43, 46, 47, 48, 50]
CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing30/Simulation6_8_30.csv
[0. 0. 0. 5. 5. 0. 0. 0. 0. 0.]
TOTAL AMOUNT WRONG: 10
PERIODS WRONG: [31, 32, 33, 34, 36, 42, 43, 46, 47, 49]
CURR

([[31, 32, 35, 36, 40, 43, 44, 45, 46, 47, 48, 94],
  [31, 32, 33, 35, 36, 37, 42, 43, 45, 46, 47, 99],
  [31, 32, 35, 36, 37, 42, 43, 46, 47, 48, 49],
  [32, 33, 35, 37, 42, 43, 44, 46, 47, 48],
  [32, 33, 35, 42, 44, 46, 49],
  [32, 33, 36, 39, 40, 43, 45, 46, 47, 48, 54, 89]],
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 6., 4., 0.,
        5., 4., 3., 0., 1., 2., 0., 4., 5., 3., 3., 6., 5., 4., 2., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]))

In [ ]:
import os
import csv

rootdir = ("/content/drive/MyDrive/Simulations/Opposing/")
rootdir2 = ("/content/drive/MyDrive/Simulations/Baseline/")
rootdir3 = ("/content/drive/MyDrive/Simulations/LastOppo/")
rootdir4 = ("/content/drive/MyDrive/Simulations/PredOppo/")


problem_groups = [3,4,6,7,8,9,15]
#for groupnumber in range(1,16):
groups_to_use = [6]

all_files = []
for groupnumber in groups_to_use:
  data_for_csv = []
  print("----------------------------------------")
  print("FOR DATA IN GROUP " + str(groupnumber))
  extra_array, index_errors1 = walk_over_directories(rootdir2, [])#, [5,10,15,20,25,30])
  full_period_array, index_errors2 = walk_over_directories(rootdir, [15])
  extra_array2, index_errors3 = walk_over_directories(rootdir3, [])
  extra_array3, index_errors4 = walk_over_directories(rootdir4, [5,25])
  index_errors = index_errors1 + index_errors2 + index_errors3 + index_errors4

  
  for i in range(len(extra_array)):
    full_period_array.append(extra_array[i])
  for i in range(len(extra_array2)):
    full_period_array.append(extra_array2[i])
  for i in range(len(extra_array3)):
    full_period_array.append(extra_array3[i])
  combine_classifiers_results(full_period_array, data_for_csv)
  filename_for_classifiers = 'Classifiers_group{}.csv'.format(groupnumber)
  all_files.append(filename_for_classifiers)
  header = ['Comb', 'Right', 'Unsure', 'Wrong']
  write_to_csv(filename_for_classifiers, data_for_csv, header)
  

  #print("AFTER ALL PERIODS: " + str(index_errors))
  #print("AND SEPERATE LOWEST AMOUNT OF ERRORS WAS: " + str(cur_lowest_errors))

#header = ['Comb', 'Right', 'Unsure', 'Wrong']
#write_to_csv('testfile.csv', data_for_csv, header)

df_total = pd.DataFrame()
for file in all_files:
     if file.endswith('.csv'):
         df_total = df_total.append(pd.read_csv(file), ignore_index=True) 
df_total.to_csv("testing_combined.csv")

'''
  max_errors = np.max(index_errors)
  wrong_counter = {}

  total = 0
  #for i in range(len(index_errors)):
  for i in range(30,100):
    amount_wrong_cur = index_errors[i]
    if amount_wrong_cur not in wrong_counter.keys():
      wrong_counter[amount_wrong_cur] = []
    wrong_counter[amount_wrong_cur].append(i+1)

  for i in sorted(wrong_counter.keys()):
    print("FOR ERRORS THAT HAPPEN " + str(i) + " THERE ARE " + str(len(wrong_counter[i])) + " NUMBERS")

  #amount_of_deciders = sorted(len(wrong_counter.keys))
  print(len(testing))
'''



100%|██████████| 8/8 [00:00<00:00, 1048.67it/s]

----------------------------------------
FOR DATA IN GROUP 6
CURRENTLY USING /content/drive/MyDrive/Simulations/Opposing/Opposing15/Simulation6_6_15.csv
[0. 0. 0. 3. 3. 1. 3. 1. 0. 0.]
TOTAL AMOUNT WRONG: 11
PERIODS WRONG: [32, 33, 36, 42, 44, 45, 55, 67, 68, 69, 74]
CURRENTLY USING /content/drive/MyDrive/Simulations/PredOppo/PredOppo25/Simulation6_6_25.csv
[0. 0. 0. 3. 5. 1. 4. 1. 0. 0.]
TOTAL AMOUNT WRONG: 14
PERIODS WRONG: [33, 36, 37, 43, 44, 46, 48, 49, 55, 67, 68, 69, 70, 71]
CURRENTLY USING /content/drive/MyDrive/Simulations/PredOppo/PredOppo5/Simulation6_6_5.csv
[0. 0. 0. 3. 4. 2. 2. 2. 1. 0.]
TOTAL AMOUNT WRONG: 14
PERIODS WRONG: [32, 34, 35, 42, 43, 46, 47, 57, 58, 67, 68, 74, 77, 89]
------------------------------------
011
RIGHT: 46    UNSURE: 20    WRONG: 4
------------------------------------
101
RIGHT: 50    UNSURE: 15    WRONG: 5
------------------------------------
110
RIGHT: 52    UNSURE: 11    WRONG: 7
------------------------------------
111
RIGHT: 45    UNSURE: 23 

'\n  max_errors = np.max(index_errors)\n  wrong_counter = {}\n\n  total = 0\n  #for i in range(len(index_errors)):\n  for i in range(30,100):\n    amount_wrong_cur = index_errors[i]\n    if amount_wrong_cur not in wrong_counter.keys():\n      wrong_counter[amount_wrong_cur] = []\n    wrong_counter[amount_wrong_cur].append(i+1)\n\n  for i in sorted(wrong_counter.keys()):\n    print("FOR ERRORS THAT HAPPEN " + str(i) + " THERE ARE " + str(len(wrong_counter[i])) + " NUMBERS")\n\n  #amount_of_deciders = sorted(len(wrong_counter.keys))\n  print(len(testing))\n'

In [ ]:
analyze_combined_stats('testing_combined.csv', 'Right')
analyze_combined_stats('testing_combined.csv', 'Wrong')
analyze_combined_stats('testing_combined.csv', 'Unsure')

In [ ]:
import os

rootdir = ("/content/drive/MyDrive/Simulations/Baseline/")


problem_groups = [3,4,6,7,8,9,15]
#for groupnumber in range(1,16):
for groupnumber in problem_groups:
  all_period_array = []
  index_errors = np.zeros(100)
  total_files = 0
  print("----------------------------------------")
  print("FOR DATA IN GROUP " + str(groupnumber))
  cur_lowest_errors = 100
  for dir in os.listdir(rootdir):
    cur_period = dir[8:]
    filename = "/Simulation6_" + str(groupnumber) + "_" + str(cur_period) + ".csv"
    Dataframe = pd.read_csv(rootdir + dir + filename )

    Period_errors = np.zeros(10)
    Periods = Dataframe['Period'].dropna().unique()

    periods_wrong = []
    Q_diff_CORRECT = []
    Q_diff_WRONG = []
    wrong = 0
    for i in Periods:
    #for i in range(31, 101):
      cur_periodic_part = np.int(np.ceil(i/10 - 1))
      iteration = Dataframe.loc[Dataframe['Period'] == i]
      occurence_count = iteration['Occurence count'].values
      if (iteration['Real action'].values == iteration['Predicted taken'].values):
        #("EQUAL")
        Q_diff_CORRECT.append(iteration['Q-value diff'])
      else:
        #("NOT EQUAL")
        #print(str(occurence_count) + " ON PERIOD: " + str(i))
        Period_errors[cur_periodic_part] +=1
        wrong += 1 
        Q_diff_WRONG.append(iteration['Q-value diff'])
        periods_wrong.append(i)
        i = np.int(i)
        index_errors[i-1] += 1

    #print(Period_errors)
    #print("MEAN Q DIFF FOR CORRECT: "  + str(np.mean(Q_diff_CORRECT)))
    #print("MEAN Q DIFF FOR WRONG: "  + str(np.mean(Q_diff_WRONG)))
    print("TOTAL AMOUNT WRONG: " + str(wrong))
    print("PERIODS WRONG: " + str(periods_wrong))
    if (len(periods_wrong) < cur_lowest_errors):
      cur_lowest_errors = len(periods_wrong)
    all_period_array.append(periods_wrong)

  print("AFTER ALL PERIODS: " + str(index_errors))
  print("AND SEPERATE LOWEST AMOUNT OF ERRORS WAS: " + str(cur_lowest_errors))



  total = 0
  for i in range(len(index_errors)):
    if index_errors[i] > 3:
      #print(i+1)
      total += 1
  print("TOTAL:" + str(total))
  percentage_correct = ((70-total)/70)*100
  print("THIS IS " + str(percentage_correct) + "% ACCURACY")

----------------------------------------
FOR DATA IN GROUP 3
TOTAL AMOUNT WRONG: 51
PERIODS WRONG: [6, 7, 8, 26, 27, 28, 31, 32, 33, 36, 38, 39, 43, 44, 45, 47, 49, 50, 51, 53, 55, 56, 57, 58, 59, 61, 63, 65, 67, 68, 69, 72, 73, 76, 77, 78, 79, 80, 81, 82, 83, 88, 89, 90, 91, 93, 94, 95, 97, 99, 100]
TOTAL AMOUNT WRONG: 42
PERIODS WRONG: [12, 13, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 41, 43, 45, 48, 49, 50, 52, 55, 56, 57, 64, 65, 69, 70, 72, 73, 75, 76, 77, 78, 80, 86, 90, 91, 93, 94, 97, 98, 99, 100]
TOTAL AMOUNT WRONG: 35
PERIODS WRONG: [29, 30, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 45, 48, 49, 54, 55, 56, 57, 58, 63, 65, 68, 70, 73, 76, 78, 79, 88, 89, 90, 93, 97, 98, 99]
TOTAL AMOUNT WRONG: 40
PERIODS WRONG: [28, 30, 31, 35, 36, 37, 42, 43, 44, 47, 48, 49, 51, 52, 53, 54, 56, 58, 59, 61, 65, 68, 70, 74, 76, 77, 78, 79, 80, 85, 87, 88, 89, 90, 91, 92, 93, 96, 97, 98]
TOTAL AMOUNT WRONG: 34
PERIODS WRONG: [30, 31, 32, 33, 34, 35, 36, 37, 39, 42, 44, 47, 49, 51, 52, 53, 54, 58, 5

KeyboardInterrupt: ignored

In [ ]:
import os
import csv

#rootdir = ("/content/drive/MyDrive/Simulations/Opposing/")
rootdir2 = ("/content/drive/MyDrive/Simulations/Baseline/")


#problem_groups = [3,4,6,7,8,9,15]
for groupnumber in range(1,16):
#data_for_csv = []
#for groupnumber in problem_groups:
  print("----------------------------------------")
  print("FOR DATA IN GROUP " + str(groupnumber))
  extra_array, index_errors1 = walk_over_directories(rootdir, [5,10,15,20,25,30])#, [5,10,15,20,25,30])
  #full_period_array, index_errors2 = walk_over_directories(rootdir2, [5,10,15,20,25,30])
  index_errors = index_errors1 

  
  '''for i in range(len(extra_array)):
    full_period_array.append(extra_array[i])
  combine_classifiers_results(full_period_array, data_for_csv)'''

  

  print("AFTER ALL PERIODS: " + str(index_errors))
  print("AND SEPERATE LOWEST AMOUNT OF ERRORS WAS: " + str(cur_lowest_errors))

#header = ['Comb', 'Right', 'Unsure', 'Wrong']
#write_to_csv('testfile.csv', data_for_csv, header)

'''
  max_errors = np.max(index_errors)
  wrong_counter = {}

  total = 0
  #for i in range(len(index_errors)):
  for i in range(30,100):
    amount_wrong_cur = index_errors[i]
    if amount_wrong_cur not in wrong_counter.keys():
      wrong_counter[amount_wrong_cur] = []
    wrong_counter[amount_wrong_cur].append(i+1)

  for i in sorted(wrong_counter.keys()):
    print("FOR ERRORS THAT HAPPEN " + str(i) + " THERE ARE " + str(len(wrong_counter[i])) + " NUMBERS")

  #amount_of_deciders = sorted(len(wrong_counter.keys))
  print(len(testing))
'''



----------------------------------------
FOR DATA IN GROUP 1
CURRENTLY USING /content/drive/MyDrive/Simulations/Baseline/Baseline10/Simulation6_1_10.csv
[0. 4. 3. 1. 0. 0. 1. 3. 0. 0.]
TOTAL AMOUNT WRONG: 12
PERIODS WRONG: [13, 15, 17, 19, 25, 26, 29, 37, 64, 78, 79, 80]
CURRENTLY USING /content/drive/MyDrive/Simulations/Baseline/Baseline15/Simulation6_1_15.csv
[0. 3. 2. 0. 0. 0. 0. 2. 0. 0.]
TOTAL AMOUNT WRONG: 7
PERIODS WRONG: [16, 18, 20, 25, 26, 78, 80]
CURRENTLY USING /content/drive/MyDrive/Simulations/Baseline/Baseline20/Simulation6_1_20.csv
[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
TOTAL AMOUNT WRONG: 4
PERIODS WRONG: [21, 25, 78, 79]
CURRENTLY USING /content/drive/MyDrive/Simulations/Baseline/Baseline25/Simulation6_1_25.csv
[0. 0. 3. 0. 0. 0. 0. 1. 0. 0.]
TOTAL AMOUNT WRONG: 4
PERIODS WRONG: [26, 27, 28, 78]
CURRENTLY USING /content/drive/MyDrive/Simulations/Baseline/Baseline30/Simulation6_1_30.csv
[0. 0. 0. 1. 0. 0. 0. 3. 0. 0.]
TOTAL AMOUNT WRONG: 4
PERIODS WRONG: [32, 78, 79, 80]
CURR

'\n  max_errors = np.max(index_errors)\n  wrong_counter = {}\n\n  total = 0\n  #for i in range(len(index_errors)):\n  for i in range(30,100):\n    amount_wrong_cur = index_errors[i]\n    if amount_wrong_cur not in wrong_counter.keys():\n      wrong_counter[amount_wrong_cur] = []\n    wrong_counter[amount_wrong_cur].append(i+1)\n\n  for i in sorted(wrong_counter.keys()):\n    print("FOR ERRORS THAT HAPPEN " + str(i) + " THERE ARE " + str(len(wrong_counter[i])) + " NUMBERS")\n\n  #amount_of_deciders = sorted(len(wrong_counter.keys))\n  print(len(testing))\n'